require(fpp2)
AntiBody = read.csv(file.choose(),header=T)
names(AntiBody)
head(AntiBody)
ABsales = ts(AntiBody$Sales,start=c(1991,7),frequency=12)
ABsales
autoplot(ABsales) + ggtitle("Monthly Antibiotic Sales") + xlab("Year") + ylab("Monthly Antibiotic Sales")
ggseasonplot(ABsales) + ylab("Sales in 1000's") + xlab("Month")
ggseasonplot(ABsales,polar=TRUE) + ylab("$ million") + ggtitle("Polar Seasonal Plot: Antibiotic Drug Sales")
ggsubseriesplot(ABsales) + ggtitle("Antibiotic Sales Subseries Plot") + xlab("Month") + ylab("Monthy Sales ($1000's)")
names(AntiBody)
boxplot(Sales~Year,data=AntiBody,xlab="Year",ylab="Sales ($1000's)")
boxplot(Sales~Month,data=AntiBody,xlab="Month",ylab="Sales ($1000's)")
