require(fpp2)
AusVisit = read.csv(file.choose(),header=T)
names(AusVisit)
str(AusVisit)
Visits = AusVisit$Visitors
Visits = ts(Visits,start=1980,frequency=1)
autoplot(Visits) + ggtitle("Number of Annual International Visitors to Australia (1980-2015)") + xlab("Year") + ylab("# of Visitors (in millions)")
fit = auto.arima(Visits)
forecast(fit,h=10)
plot(forecast(fit,h=10),xlab="Year",ylab="# of Annual Visitors (millions)")
fit %>% forecast(h=10) %>% autoplot() + xlab("Year") + ylab("# of Visitors (millions)")
