require(fpp2)
require(GGally)
uschange
autoplot(uschange,facet=T)
USchange = as.data.frame(uschange)
names(USchange)
ggpairs(USchange)
mod1 = lm(Consumption~Income,data=USchange)
plot(Consumption~Income,data=USchange)
abline(mod1,lwd=1,col="blue")
par(mfrow=c(2,2))
plot(mod1)
par(mfrow=c(1,1))
checkresiduals(mod1)
summary(mod1)

mod2 = lm(Consumption ~ Income + Production + Savings + Unemployment, data = USchange)
par(mfrow=c(2,2))
plot(mod2)
par(mfrow=c(1,1))
checkresiduals(mod2)
summary(mod2)

mod3 = lm(Consumption ~ Income + Savings + Unemployment,data=USchange)
par(mfrow=c(2,2))
plot(mod3)
checkresiduals(mod3)
summary(mod3)

